# Generated by Django 4.1.5 on 2023-03-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_address_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
