# Generated by Django 4.1.5 on 2023-03-02 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_address_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='building_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='flat_no',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
