# Generated by Django 4.1.5 on 2023-03-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_address_building_name_address_flat_no_address_street'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entries'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit',
        ),
        migrations.AddField(
            model_name='credit',
            name='customers',
            field=models.ManyToManyField(to='credit.customer'),
        ),
    ]
