# Generated by Django 4.1.5 on 2023-03-02 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0010_alter_address_options_remove_customer_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='image_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='customers',
            field=models.ManyToManyField(related_name='credits', to='credit.customer'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
