# Generated by Django 4.1.5 on 2023-03-03 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0011_credit_image_name_alter_credit_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='salary',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinValueValidator(10000)]),
        ),
    ]
