# Generated by Django 4.1.5 on 2023-03-03 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0012_customer_job_title_customer_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='salary',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(10000)]),
        ),
    ]
