# Generated by Django 4.1.5 on 2023-03-04 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0013_alter_customer_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identification_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(11111111111), django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
