# Generated by Django 4.1.5 on 2023-03-05 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0014_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identification_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinValueValidator(11111111111), django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
