# Generated by Django 4.1.5 on 2023-03-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0015_alter_customer_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identification_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
