# Generated by Django 4.1.5 on 2023-03-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0016_alter_customer_identification_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='flat_no',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='customers',
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('credit_types', models.ManyToManyField(related_name='banks', to='credit.credit')),
            ],
        ),
    ]
