# Generated by Django 4.1.5 on 2023-03-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0017_remove_address_building_name_remove_address_flat_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='credit_types',
            field=models.ManyToManyField(to='credit.credit'),
        ),
    ]
