# Generated by Django 4.1.5 on 2023-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0018_bank_slug_alter_bank_credit_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
    ]
