# Generated by Django 4.1.5 on 2023-03-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0020_rename_slug_bank_bank_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
