# Generated by Django 4.1.5 on 2023-03-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0021_delete_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_slug', models.SlugField(default='', unique=True)),
                ('credit_types', models.ManyToManyField(to='credit.credit')),
            ],
        ),
    ]
