# Generated by Django 4.1.5 on 2023-03-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0022_bank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank',
            new_name='Bank_Option',
        ),
    ]
