# Generated by Django 4.1.5 on 2023-03-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0024_rename_bank_name_bank_option_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank_Option',
            new_name='BankOption',
        ),
    ]
