# Generated by Django 4.1.5 on 2023-03-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0025_rename_bank_option_bankoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankoption',
            name='credit_types',
        ),
        migrations.AddField(
            model_name='bankoption',
            name='credit_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.credit'),
        ),
    ]
