# Generated by Django 4.1.5 on 2023-03-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0028_alter_customer_identification_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
