# Generated by Django 4.1.5 on 2023-03-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0029_remove_address_postal_code_remove_address_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('credit_name', models.CharField(max_length=50)),
                ('identification_number', models.OneToOneField(error_messages={'unique': 'This identification number has been already registered!'}, max_length=11, on_delete=django.db.models.deletion.CASCADE, to='credit.customer')),
            ],
        ),
    ]
