# Generated by Django 4.1.5 on 2023-03-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0030_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='identification_number',
            field=models.CharField(error_messages={'unique': 'This identification number has been already registered!'}, max_length=11, unique=True),
        ),
    ]
