# Generated by Django 4.1.5 on 2023-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0031_alter_application_identification_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.AddField(
            model_name='customer',
            name='bank',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
